// Real phone specifications — hardcoded, no external API dependency

export type PhoneSpec = {
  id: string;
  brand: "Apple" | "Samsung" | "Xiaomi" | "Oppo" | "Vivo" | "Realme";
  name: string;
  launchYear: number;
  priceRange: string;
  imageUrl: string;
  specs: {
    // Display
    screenSize: string;
    resolution: string;
    displayType: string;
    refreshRate: string;
    brightness: string;
    // Performance
    processor: string;
    gpu: string;
    ram: string;
    storage: string;
    // Camera
    mainCamera: string;
    ultrawide: string;
    telephoto: string;
    frontCamera: string;
    videoMax: string;
    // Battery
    batteryCapacity: string;
    charging: string;
    // Body
    weight: string;
    dimensions: string;
    build: string;
    ipRating: string;
    // Connectivity
    network: string;
    wifi: string;
    bluetooth: string;
    nfc: string;
    usb: string;
    // Features
    fingerprint: string;
    faceUnlock: string;
    wirelessCharging: string;
    reverseCharging: string;
    simSlots: string;
  };
};

export const phones: PhoneSpec[] = [
  // ── APPLE iPhone ──────────────────────────────────────
  {
    id: "iphone-16-pro-max",
    brand: "Apple",
    name: "iPhone 16 Pro Max",
    launchYear: 2025,
    priceRange: "Rp 23jt - 27jt",
    imageUrl: "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=400&q=80",
    specs: {
      screenSize: "6.9 inci",
      resolution: "2868 x 1320 px (460 ppi)",
      displayType: "Super Retina XDR OLED",
      refreshRate: "1-120Hz ProMotion LTPO",
      brightness: "Up to 2000 nits (outdoor)",
      processor: "Apple A18 Pro (3nm)",
      gpu: "Apple GPU 6-core",
      ram: "8 GB",
      storage: "256 GB / 512 GB / 1 TB",
      mainCamera: "48 MP f/1.78 (Fusion), sensor-shift OIS",
      ultrawide: "48 MP f/2.2, 120° FoV",
      telephoto: "12 MP f/2.8, 5x optical zoom",
      frontCamera: "12 MP f/1.9, autofocus",
      videoMax: "4K 120fps Dolby Vision, ProRes LOG",
      batteryCapacity: "4685 mAh",
      charging: "USB-C 45W wired, 25W MagSafe wireless",
      weight: "227 g",
      dimensions: "163 x 77.6 x 8.25 mm",
      build: "Grade 5 titanium, Ceramic Shield front",
      ipRating: "IP68 (6m, 30 min)",
      network: "5G (sub-6 + mmWave), LTE-A",
      wifi: "Wi-Fi 7 (802.11be)",
      bluetooth: "5.3",
      nfc: "Ya (Apple Pay)",
      usb: "USB 3.2 Gen 2 (10 Gbps)",
      fingerprint: "Tidak",
      faceUnlock: "Face ID (TrueDepth)",
      wirelessCharging: "Ya, MagSafe 25W / Qi2 15W",
      reverseCharging: "Ya, 5W",
      simSlots: "Dual SIM (nano + eSIM)",
    },
  },
  {
    id: "iphone-16-pro",
    brand: "Apple",
    name: "iPhone 16 Pro",
    launchYear: 2025,
    priceRange: "Rp 18jt - 22jt",
    imageUrl: "https://images.unsplash.com/photo-1592750475338-5f1d4a2e6f6b?w=400&q=80",
    specs: {
      screenSize: "6.3 inci",
      resolution: "2622 x 1206 px (460 ppi)",
      displayType: "Super Retina XDR OLED",
      refreshRate: "1-120Hz ProMotion LTPO",
      brightness: "Up to 2000 nits (outdoor)",
      processor: "Apple A18 Pro (3nm)",
      gpu: "Apple GPU 6-core",
      ram: "8 GB",
      storage: "128 GB / 256 GB / 512 GB / 1 TB",
      mainCamera: "48 MP f/1.78 (Fusion), sensor-shift OIS",
      ultrawide: "48 MP f/2.2, 120° FoV",
      telephoto: "12 MP f/2.8, 5x optical zoom",
      frontCamera: "12 MP f/1.9, autofocus",
      videoMax: "4K 120fps Dolby Vision, ProRes LOG",
      batteryCapacity: "3582 mAh",
      charging: "USB-C 45W wired, 25W MagSafe wireless",
      weight: "199 g",
      dimensions: "149.6 x 71.5 x 8.25 mm",
      build: "Grade 5 titanium, Ceramic Shield front",
      ipRating: "IP68 (6m, 30 min)",
      network: "5G (sub-6 + mmWave), LTE-A",
      wifi: "Wi-Fi 7 (802.11be)",
      bluetooth: "5.3",
      nfc: "Ya (Apple Pay)",
      usb: "USB 3.2 Gen 2 (10 Gbps)",
      fingerprint: "Tidak",
      faceUnlock: "Face ID (TrueDepth)",
      wirelessCharging: "Ya, MagSafe 25W / Qi2 15W",
      reverseCharging: "Ya, 5W",
      simSlots: "Dual SIM (nano + eSIM)",
    },
  },
  {
    id: "iphone-16",
    brand: "Apple",
    name: "iPhone 16",
    launchYear: 2025,
    priceRange: "Rp 13jt - 17jt",
    imageUrl: "https://images.unsplash.com/photo-1603891128711-11b4b03bb138?w=400&q=80",
    specs: {
      screenSize: "6.1 inci",
      resolution: "2556 x 1179 px (460 ppi)",
      displayType: "Super Retina XDR OLED",
      refreshRate: "60Hz / Up to 120Hz (Game Mode)",
      brightness: "Up to 2000 nits (outdoor)",
      processor: "Apple A18 (3nm)",
      gpu: "Apple GPU 5-core",
      ram: "8 GB",
      storage: "128 GB / 256 GB / 512 GB",
      mainCamera: "48 MP f/1.6, sensor-shift OIS",
      ultrawide: "12 MP f/2.2, 120° FoV",
      telephoto: "Tidak (digital zoom 10x)",
      frontCamera: "12 MP f/1.9, autofocus",
      videoMax: "4K 60fps Dolby Vision",
      batteryCapacity: "3561 mAh",
      charging: "USB-C 45W wired, 25W MagSafe wireless",
      weight: "170 g",
      dimensions: "147.6 x 71.6 x 7.80 mm",
      build: "Aluminium + Color-infused glass",
      ipRating: "IP68 (6m, 30 min)",
      network: "5G (sub-6), LTE-A",
      wifi: "Wi-Fi 7 (802.11be)",
      bluetooth: "5.3",
      nfc: "Ya (Apple Pay)",
      usb: "USB 2.0 (480 Mbps)",
      fingerprint: "Tidak",
      faceUnlock: "Face ID (TrueDepth)",
      wirelessCharging: "Ya, MagSafe 25W / Qi2 15W",
      reverseCharging: "Ya, 5W",
      simSlots: "Dual SIM (nano + eSIM)",
    },
  },
  {
    id: "iphone-15-pro-max",
    brand: "Apple",
    name: "iPhone 15 Pro Max",
    launchYear: 2024,
    priceRange: "Rp 20jt - 24jt",
    imageUrl: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400&q=80",
    specs: {
      screenSize: "6.7 inci",
      resolution: "2796 x 1290 px (460 ppi)",
      displayType: "Super Retina XDR OLED",
      refreshRate: "1-120Hz ProMotion LTPO",
      brightness: "Up to 2000 nits (outdoor)",
      processor: "Apple A17 Pro (3nm)",
      gpu: "Apple GPU 6-core",
      ram: "8 GB",
      storage: "256 GB / 512 GB / 1 TB",
      mainCamera: "48 MP f/1.78 (Fusion), sensor-shift OIS",
      ultrawide: "12 MP f/2.2, 120° FoV",
      telephoto: "12 MP f/2.8, 5x optical zoom",
      frontCamera: "12 MP f/1.9, autofocus",
      videoMax: "4K 60fps Dolby Vision, ProRes LOG",
      batteryCapacity: "4422 mAh",
      charging: "USB-C 45W wired, 25W MagSafe wireless",
      weight: "221 g",
      dimensions: "159.9 x 76.7 x 8.25 mm",
      build: "Grade 5 titanium, Ceramic Shield front",
      ipRating: "IP68 (6m, 30 min)",
      network: "5G (sub-6 + mmWave), LTE-A",
      wifi: "Wi-Fi 6E (802.11ax)",
      bluetooth: "5.3",
      nfc: "Ya (Apple Pay)",
      usb: "USB 3.2 Gen 2 (10 Gbps)",
      fingerprint: "Tidak",
      faceUnlock: "Face ID (TrueDepth)",
      wirelessCharging: "Ya, MagSafe 25W / Qi 15W",
      reverseCharging: "Ya, 5W",
      simSlots: "Dual SIM (nano + eSIM)",
    },
  },
  {
    id: "iphone-15",
    brand: "Apple",
    name: "iPhone 15",
    launchYear: 2024,
    priceRange: "Rp 12jt - 15jt",
    imageUrl: "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=400&q=80",
    specs: {
      screenSize: "6.1 inci",
      resolution: "2556 x 1179 px (460 ppi)",
      displayType: "Super Retina XDR OLED",
      refreshRate: "60Hz",
      brightness: "Up to 2000 nits (outdoor)",
      processor: "Apple A16 Bionic (4nm)",
      gpu: "Apple GPU 5-core",
      ram: "6 GB",
      storage: "128 GB / 256 GB / 512 GB",
      mainCamera: "48 MP f/1.6, sensor-shift OIS",
      ultrawide: "12 MP f/2.2, 120° FoV",
      telephoto: "Tidak (digital zoom 10x)",
      frontCamera: "12 MP f/1.9, autofocus",
      videoMax: "4K 60fps Dolby Vision",
      batteryCapacity: "3349 mAh",
      charging: "USB-C 45W wired, 15W MagSafe wireless",
      weight: "171 g",
      dimensions: "147.6 x 71.6 x 7.80 mm",
      build: "Aluminium, Color-infused glass back",
      ipRating: "IP68 (6m, 30 min)",
      network: "5G (sub-6), LTE-A",
      wifi: "Wi-Fi 6 (802.11ax)",
      bluetooth: "5.3",
      nfc: "Ya (Apple Pay)",
      usb: "USB 2.0 (480 Mbps)",
      fingerprint: "Tidak",
      faceUnlock: "Face ID (TrueDepth)",
      wirelessCharging: "Ya, MagSafe 15W / Qi 7.5W",
      reverseCharging: "Ya, 5W",
      simSlots: "Dual SIM (nano + eSIM)",
    },
  },
  {
    id: "iphone-14-pro",
    brand: "Apple",
    name: "iPhone 14 Pro",
    launchYear: 2023,
    priceRange: "Rp 15jt - 20jt",
    imageUrl: "https://images.unsplash.com/photo-1603891128711-11b4b03bb138?w=400&q=80",
    specs: {
      screenSize: "6.1 inci",
      resolution: "2556 x 1179 px (460 ppi)",
      displayType: "Super Retina XDR OLED + Always-On",
      refreshRate: "1-120Hz ProMotion LTPO",
      brightness: "Up to 2000 nits (outdoor)",
      processor: "Apple A16 Bionic (4nm)",
      gpu: "Apple GPU 5-core",
      ram: "6 GB",
      storage: "128 GB / 256 GB / 512 GB / 1 TB",
      mainCamera: "48 MP f/1.78, sensor-shift OIS",
      ultrawide: "12 MP f/2.2, 120° FoV",
      telephoto: "12 MP f/2.8, 3x optical zoom",
      frontCamera: "12 MP f/1.9, autofocus",
      videoMax: "4K 60fps Dolby Vision, ProRes LOG",
      batteryCapacity: "3200 mAh",
      charging: "Lightning 30W, 15W MagSafe wireless",
      weight: "206 g",
      dimensions: "147.5 x 71.5 x 7.85 mm",
      build: "Stainless steel, Ceramic Shield front",
      ipRating: "IP68 (6m, 30 min)",
      network: "5G (sub-6), LTE-A",
      wifi: "Wi-Fi 6 (802.11ax)",
      bluetooth: "5.3",
      nfc: "Ya (Apple Pay)",
      usb: "Lightning (USB 2.0)",
      fingerprint: "Tidak",
      faceUnlock: "Face ID (TrueDepth)",
      wirelessCharging: "Ya, MagSafe 15W / Qi 7.5W",
      reverseCharging: "Ya, 5W",
      simSlots: "Dual SIM (nano + eSIM)",
    },
  },

  // ── SAMSUNG ───────────────────────────────────────────
  {
    id: "samsung-s24-ultra",
    brand: "Samsung",
    name: "Galaxy S24 Ultra",
    launchYear: 2025,
    priceRange: "Rp 21jt - 25jt",
    imageUrl: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400&q=80",
    specs: {
      screenSize: "6.8 inci",
      resolution: "3120 x 1440 px (QHD+, 505 ppi)",
      displayType: "Dynamic LTPO AMOLED 2X",
      refreshRate: "1-120Hz Adaptive",
      brightness: "Up to 2600 nits (outdoor)",
      processor: "Snapdragon 8 Gen 3 for Galaxy (4nm)",
      gpu: "Adreno 750",
      ram: "12 GB",
      storage: "256 GB / 512 GB / 1 TB",
      mainCamera: "200 MP f/1.7, OIS",
      ultrawide: "12 MP f/2.2, 120° FoV",
      telephoto: "50 MP f/3.4 (5x) + 10 MP f/2.4 (3x)",
      frontCamera: "12 MP f/2.2, autofocus",
      videoMax: "8K 30fps, 4K 120fps",
      batteryCapacity: "5000 mAh",
      charging: "45W wired, 15W wireless",
      weight: "233 g",
      dimensions: "162.3 x 79.0 x 8.6 mm",
      build: "Titanium frame, Gorilla Armor glass",
      ipRating: "IP68",
      network: "5G (sub-6 + mmWave), LTE-A",
      wifi: "Wi-Fi 7 (802.11be)",
      bluetooth: "5.3",
      nfc: "Ya",
      usb: "USB 3.2 Gen 1 (10 Gbps), USB-C",
      fingerprint: "Ultrasonic in-display",
      faceUnlock: "Ya (Face)",
      wirelessCharging: "Ya, 15W Qi / PMA",
      reverseCharging: "Ya, 4.5W",
      simSlots: "Dual SIM (nano + eSIM)",
    },
  },
  {
    id: "samsung-s24-plus",
    brand: "Samsung",
    name: "Galaxy S24+",
    launchYear: 2025,
    priceRange: "Rp 15jt - 19jt",
    imageUrl: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400&q=80",
    specs: {
      screenSize: "6.7 inci",
      resolution: "3120 x 1440 px (QHD+, 513 ppi)",
      displayType: "Dynamic LTPO AMOLED 2X",
      refreshRate: "1-120Hz Adaptive",
      brightness: "Up to 2600 nits (outdoor)",
      processor: "Snapdragon 8 Gen 3 for Galaxy (4nm)",
      gpu: "Adreno 750",
      ram: "12 GB",
      storage: "256 GB / 512 GB",
      mainCamera: "50 MP f/1.8, OIS",
      ultrawide: "12 MP f/2.2, 120° FoV",
      telephoto: "10 MP f/2.4 (3x optical zoom)",
      frontCamera: "12 MP f/2.2, autofocus",
      videoMax: "8K 30fps, 4K 60fps",
      batteryCapacity: "4900 mAh",
      charging: "45W wired, 15W wireless",
      weight: "196 g",
      dimensions: "158.5 x 75.9 x 7.7 mm",
      build: "Aluminium Armor, Gorilla Glass Victus 2",
      ipRating: "IP68",
      network: "5G (sub-6), LTE-A",
      wifi: "Wi-Fi 6E (802.11ax)",
      bluetooth: "5.3",
      nfc: "Ya",
      usb: "USB 3.2 Gen 1 (10 Gbps), USB-C",
      fingerprint: "Ultrasonic in-display",
      faceUnlock: "Ya (Face)",
      wirelessCharging: "Ya, 15W Qi / PMA",
      reverseCharging: "Ya, 4.5W",
      simSlots: "Dual SIM (nano + eSIM)",
    },
  },
  {
    id: "samsung-s24",
    brand: "Samsung",
    name: "Galaxy S24",
    launchYear: 2025,
    priceRange: "Rp 12jt - 15jt",
    imageUrl: "https://images.unsplash.com/photo-1563191911-e65f4c9e80b2?w=400&q=80",
    specs: {
      screenSize: "6.2 inci",
      resolution: "2340 x 1080 px (FHD+, 418 ppi)",
      displayType: "Dynamic LTPO AMOLED 2X",
      refreshRate: "1-120Hz Adaptive",
      brightness: "Up to 2600 nits (outdoor)",
      processor: "Snapdragon 8 Gen 3 for Galaxy (4nm)",
      gpu: "Adreno 750",
      ram: "8 GB",
      storage: "128 GB / 256 GB",
      mainCamera: "50 MP f/1.8, OIS",
      ultrawide: "12 MP f/2.2, 120° FoV",
      telephoto: "10 MP f/2.4 (3x optical zoom)",
      frontCamera: "12 MP f/2.2, autofocus",
      videoMax: "8K 30fps, 4K 60fps",
      batteryCapacity: "4000 mAh",
      charging: "25W wired, 15W wireless",
      weight: "167 g",
      dimensions: "147.0 x 70.6 x 7.6 mm",
      build: "Aluminium Armor, Gorilla Glass Victus 2",
      ipRating: "IP68",
      network: "5G (sub-6), LTE-A",
      wifi: "Wi-Fi 6E (802.11ax)",
      bluetooth: "5.3",
      nfc: "Ya",
      usb: "USB 3.2 Gen 1 (10 Gbps), USB-C",
      fingerprint: "Ultrasonic in-display",
      faceUnlock: "Ya (Face)",
      wirelessCharging: "Ya, 15W Qi / PMA",
      reverseCharging: "Ya, 4.5W",
      simSlots: "Dual SIM (nano + eSIM)",
    },
  },
  {
    id: "samsung-z-fold6",
    brand: "Samsung",
    name: "Galaxy Z Fold6",
    launchYear: 2025,
    priceRange: "Rp 25jt - 30jt",
    imageUrl: "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=400&q=80",
    specs: {
      screenSize: "6.3 inci (cover) / 7.6 inci (fold-out)",
      resolution: "2376 x 968 (cover) / 2160 x 1856 (fold)",
      displayType: "Dynamic AMOLED 2X, Foldable",
      refreshRate: "1-120Hz Adaptive",
      brightness: "Up to 2600 nits (outdoor)",
      processor: "Snapdragon 8 Gen 3 for Galaxy (4nm)",
      gpu: "Adreno 750",
      ram: "12 GB",
      storage: "256 GB / 512 GB / 1 TB",
      mainCamera: "50 MP f/1.8, OIS",
      ultrawide: "12 MP f/2.2, 123° FoV",
      telephoto: "10 MP f/2.4 (3x optical zoom)",
      frontCamera: "10 MP (cover) + 4 MP UPC (fold)",
      videoMax: "8K 30fps, 4K 60fps",
      batteryCapacity: "4400 mAh",
      charging: "25W wired, 15W wireless",
      weight: "239 g",
      dimensions: "153.5 x 132.6 x 5.6 mm (unfolded) / 153.5 x 68.1 x 12.1 mm (folded)",
      build: "Aluminium frame, Gorilla Glass Victus 2",
      ipRating: "IP48",
      network: "5G (sub-6), LTE-A",
      wifi: "Wi-Fi 6E (802.11ax)",
      bluetooth: "5.3",
      nfc: "Ya",
      usb: "USB 3.2 Gen 1 (10 Gbps), USB-C",
      fingerprint: "Side-mounted capacitive",
      faceUnlock: "Ya (Face)",
      wirelessCharging: "Ya, 15W Qi / PMA",
      reverseCharging: "Ya, 4.5W",
      simSlots: "Dual SIM (nano + eSIM)",
    },
  },
  {
    id: "samsung-a55",
    brand: "Samsung",
    name: "Galaxy A55",
    launchYear: 2024,
    priceRange: "Rp 4jt - 6jt",
    imageUrl: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400&q=80",
    specs: {
      screenSize: "6.6 inci",
      resolution: "2340 x 1080 px (FHD+, 390 ppi)",
      displayType: "Super AMOLED",
      refreshRate: "120Hz",
      brightness: "Up to 1000 nits",
      processor: "Samsung Exynos 1480 (4nm)",
      gpu: "Xclipse 530",
      ram: "8 GB / 12 GB",
      storage: "128 GB / 256 GB (+ microSD up to 1TB)",
      mainCamera: "50 MP f/1.8, OIS",
      ultrawide: "12 MP f/2.2, 123° FoV",
      telephoto: "Tidak (digital zoom 4x)",
      frontCamera: "32 MP f/2.2",
      videoMax: "4K 30fps",
      batteryCapacity: "5000 mAh",
      charging: "25W wired",
      weight: "213 g",
      dimensions: "161.1 x 77.4 x 8.2 mm",
      build: "Glass back (Gorilla Glass), Metal frame",
      ipRating: "IP67",
      network: "5G, LTE-A",
      wifi: "Wi-Fi 6 (802.11ax)",
      bluetooth: "5.3",
      nfc: "Ya",
      usb: "USB 2.0, USB-C",
      fingerprint: "In-display optical",
      faceUnlock: "Ya",
      wirelessCharging: "Tidak",
      reverseCharging: "Ya (wired 5W)",
      simSlots: "Hybrid: nano-SIM + microSD / eSIM",
    },
  },

  // ── XIAOMI ────────────────────────────────────────────
  {
    id: "xiaomi-15-ultra",
    brand: "Xiaomi",
    name: "Xiaomi 15 Ultra",
    launchYear: 2025,
    priceRange: "Rp 16jt - 20jt",
    imageUrl: "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=400&q=80",
    specs: {
      screenSize: "6.73 inci",
      resolution: "3200 x 1440 px (QHD+, 522 ppi)",
      displayType: "LTPO AMOLED (Honor)/AMOLED 12-bit",
      refreshRate: "1-120Hz Adaptive",
      brightness: "Up to 3200 nits (outdoor)",
      processor: "Snapdragon 8 Elite (3nm)",
      gpu: "Adreno 830",
      ram: "16 GB",
      storage: "512 GB / 1 TB",
      mainCamera: "50 MP f/1.62, OIS, Leica optics",
      ultrawide: "50 MP f/2.2, 115° FoV",
      telephoto: "200 MP f/1.27 (periscope 5x), OIS",
      frontCamera: "32 MP f/2.0",
      videoMax: "8K 30fps, 4K 120fps",
      batteryCapacity: "5410 mAh",
      charging: "90W wired, 80W MagSafe wireless",
      weight: "229 g",
      dimensions: "161.3 x 75.3 x 9.48 mm",
      build: "Titanium grade 5, Glass back",
      ipRating: "IP68",
      network: "5G (sub-6), LTE-A",
      wifi: "Wi-Fi 7 (802.11be)",
      bluetooth: "5.4",
      nfc: "Ya",
      usb: "USB 3.2 Gen 2 (10 Gbps), USB-C",
      fingerprint: "Ultrasonic in-display",
      faceUnlock: "Ya",
      wirelessCharging: "Ya, 80W",
      reverseCharging: "Ya, 10W",
      simSlots: "Dual SIM (nano + nano)",
    },
  },
  {
    id: "xiaomi-15",
    brand: "Xiaomi",
    name: "Xiaomi 15",
    launchYear: 2025,
    priceRange: "Rp 11jt - 14jt",
    imageUrl: "https://images.unsplash.com/photo-1603891128711-11b4b03bb138?w=400&q=80",
    specs: {
      screenSize: "6.36 inci",
      resolution: "2670 x 1200 px (FHD+, 460 ppi)",
      displayType: "LTPO AMOLED",
      refreshRate: "1-120Hz Adaptive",
      brightness: "Up to 3200 nits (outdoor)",
      processor: "Snapdragon 8 Elite (3nm)",
      gpu: "Adreno 830",
      ram: "12 GB / 16 GB",
      storage: "256 GB / 512 GB / 1 TB",
      mainCamera: "50 MP f/1.62, OIS, Leica optics",
      ultrawide: "50 MP f/2.2, 115° FoV",
      telephoto: "50 MP f/2.0 (3.2x zoom), OIS",
      frontCamera: "32 MP f/2.0",
      videoMax: "8K 30fps, 4K 60fps",
      batteryCapacity: "5400 mAh",
      charging: "90W wired, 50W MagSafe wireless",
      weight: "191 g",
      dimensions: "152.3 x 71.2 x 8.08 mm",
      build: "Aluminium frame, Glass back",
      ipRating: "IP68",
      network: "5G (sub-6), LTE-A",
      wifi: "Wi-Fi 7 (802.11be)",
      bluetooth: "5.4",
      nfc: "Ya",
      usb: "USB 3.2 Gen 2 (10 Gbps), USB-C",
      fingerprint: "Ultrasonic in-display",
      faceUnlock: "Ya",
      wirelessCharging: "Ya, 50W",
      reverseCharging: "Ya, 10W",
      simSlots: "Dual SIM (nano + nano)",
    },
  },
  {
    id: "poco-f6-pro",
    brand: "Xiaomi",
    name: "POCO F6 Pro",
    launchYear: 2024,
    priceRange: "Rp 5jt - 7jt",
    imageUrl: "https://images.unsplash.com/photo-1563191911-e65f4c9e80b2?w=400&q=80",
    specs: {
      screenSize: "6.67 inci",
      resolution: "3200 x 1440 px (QHD+, 526 ppi)",
      displayType: "AMOLED 12-bit, Dolby Vision",
      refreshRate: "120Hz",
      brightness: "Up to 4000 nits (peak)",
      processor: "Snapdragon 8 Gen 2 (4nm)",
      gpu: "Adreno 740",
      ram: "12 GB / 16 GB",
      storage: "256 GB / 512 GB / 1 TB",
      mainCamera: "50 MP f/1.65, OIS",
      ultrawide: "8 MP f/2.2, 119° FoV",
      telephoto: "Tidak (digital zoom 10x)",
      frontCamera: "16 MP f/2.0",
      videoMax: "8K 24fps, 4K 60fps",
      batteryCapacity: "5000 mAh",
      charging: "120W HyperCharge (wired)",
      weight: "209 g",
      dimensions: "160.9 x 74.3 x 8.2 mm",
      build: "Aluminium frame, Glass back",
      ipRating: "IP54",
      network: "5G, LTE-A",
      wifi: "Wi-Fi 7 (802.11be)",
      bluetooth: "5.3",
      nfc: "Ya",
      usb: "USB 2.0, USB-C",
      fingerprint: "In-display optical",
      faceUnlock: "Ya",
      wirelessCharging: "Tidak",
      reverseCharging: "Ya (wired 5W)",
      simSlots: "Dual SIM (nano + nano)",
    },
  },
  {
    id: "redmi-note-14-pro-plus",
    brand: "Xiaomi",
    name: "Redmi Note 14 Pro+",
    launchYear: 2025,
    priceRange: "Rp 4jt - 6jt",
    imageUrl: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400&q=80",
    specs: {
      screenSize: "6.67 inci",
      resolution: "2712 x 1220 px (1.5K, 446 ppi)",
      displayType: "AMOLED 120Hz, Dolby Vision",
      refreshRate: "120Hz",
      brightness: "Up to 3000 nits (peak)",
      processor: "MediaTek Dimensity 7300 Ultra (4nm)",
      gpu: "Mali-G615 MC6",
      ram: "8 GB / 12 GB",
      storage: "256 GB / 512 GB",
      mainCamera: "200 MP f/1.65, OIS",
      ultrawide: "8 MP f/2.2, 120° FoV",
      telephoto: "Tidak (digital zoom 4x)",
      frontCamera: "20 MP f/2.2",
      videoMax: "4K 30fps",
      batteryCapacity: "5110 mAh",
      charging: "120W HyperCharge (wired)",
      weight: "205 g",
      dimensions: "162.7 x 74.7 x 8.8 mm",
      build: "Glass back, Plastic frame",
      ipRating: "IP68",
      network: "5G, LTE-A",
      wifi: "Wi-Fi 6 (802.11ax)",
      bluetooth: "5.3",
      nfc: "Ya",
      usb: "USB 2.0, USB-C",
      fingerprint: "In-display optical",
      faceUnlock: "Ya",
      wirelessCharging: "Tidak",
      reverseCharging: "Ya (wired 5W)",
      simSlots: "Hybrid: nano-SIM + microSD",
    },
  },

  // ── OPPO ──────────────────────────────────────────────
  {
    id: "oppo-find-x8-ultra",
    brand: "Oppo",
    name: "Find X8 Ultra",
    launchYear: 2025,
    priceRange: "Rp 18jt - 22jt",
    imageUrl: "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=400&q=80",
    specs: {
      screenSize: "6.82 inci",
      resolution: "3168 x 1440 px (QHD+, 510 ppi)",
      displayType: "LTPO AMOLED, Dolby Vision",
      refreshRate: "1-120Hz Adaptive",
      brightness: "Up to 4500 nits (peak)",
      processor: "MediaTek Dimensity 9400 (3nm)",
      gpu: "Immortalis-G925 MC12",
      ram: "16 GB",
      storage: "512 GB / 1 TB",
      mainCamera: "50 MP f/1.8, OIS, Hasselblad",
      ultrawide: "50 MP f/2.0, 120° FoV",
      telephoto: "50 MP f/2.1 (3x) + 50 MP f/2.5 (6x periscope)",
      frontCamera: "32 MP f/2.4, autofocus",
      videoMax: "4K 120fps Dolby Vision",
      batteryCapacity: "6100 mAh",
      charging: "100W SUPERVOOC wired, 50W AirVOOC wireless",
      weight: "226 g",
      dimensions: "163.1 x 77.5 x 8.78 mm",
      build: "Glass back, Aluminium frame",
      ipRating: "IP69 + IP68",
      network: "5G (sub-6), LTE-A",
      wifi: "Wi-Fi 7 (802.11be)",
      bluetooth: "5.4",
      nfc: "Ya",
      usb: "USB 3.2 Gen 1 (10 Gbps), USB-C",
      fingerprint: "Ultrasonic in-display",
      faceUnlock: "Ya",
      wirelessCharging: "Ya, 50W AirVOOC",
      reverseCharging: "Ya, 10W",
      simSlots: "Dual SIM (nano + nano)",
    },
  },
  {
    id: "oppo-find-x8-pro",
    brand: "Oppo",
    name: "Find X8 Pro",
    launchYear: 2025,
    priceRange: "Rp 14jt - 17jt",
    imageUrl: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400&q=80",
    specs: {
      screenSize: "6.78 inci",
      resolution: "2780 x 1264 px (FHD+, 450 ppi)",
      displayType: "LTPO AMOLED, Dolby Vision",
      refreshRate: "1-120Hz Adaptive",
      brightness: "Up to 4500 nits (peak)",
      processor: "MediaTek Dimensity 9400 (3nm)",
      gpu: "Immortalis-G925 MC12",
      ram: "16 GB",
      storage: "256 GB / 512 GB",
      mainCamera: "50 MP f/1.8, OIS, Hasselblad",
      ultrawide: "50 MP f/2.0, 120° FoV",
      telephoto: "50 MP f/2.1 (3x), OIS",
      frontCamera: "32 MP f/2.4, autofocus",
      videoMax: "4K 60fps Dolby Vision",
      batteryCapacity: "5910 mAh",
      charging: "80W SUPERVOOC wired, 50W AirVOOC wireless",
      weight: "215 g",
      dimensions: "162.8 x 76.1 x 8.2 mm",
      build: "Glass back, Aluminium frame",
      ipRating: "IP69 + IP68",
      network: "5G (sub-6), LTE-A",
      wifi: "Wi-Fi 7 (802.11be)",
      bluetooth: "5.4",
      nfc: "Ya",
      usb: "USB 3.2 Gen 1 (10 Gbps), USB-C",
      fingerprint: "Ultrasonic in-display",
      faceUnlock: "Ya",
      wirelessCharging: "Ya, 50W AirVOOC",
      reverseCharging: "Ya, 10W",
      simSlots: "Dual SIM (nano + nano)",
    },
  },
  {
    id: "oppo-reno-13-pro",
    brand: "Oppo",
    name: "Reno 13 Pro",
    launchYear: 2025,
    priceRange: "Rp 6jt - 8jt",
    imageUrl: "https://images.unsplash.com/photo-1603891128711-11b4b03bb138?w=400&q=80",
    specs: {
      screenSize: "6.83 inci",
      resolution: "2800 x 1272 px (FHD+, 450 ppi)",
      displayType: "AMOLED 120Hz, Dolby Vision",
      refreshRate: "120Hz",
      brightness: "Up to 1200 nits (HBM)",
      processor: "MediaTek Dimensity 8350 (4nm)",
      gpu: "Mali-G615 MC6",
      ram: "12 GB",
      storage: "256 GB / 512 GB",
      mainCamera: "50 MP f/1.8, OIS",
      ultrawide: "8 MP f/2.2, 115° FoV",
      telephoto: "50 MP f/2.0 (3.5x periscope), OIS",
      frontCamera: "50 MP f/2.0, autofocus",
      videoMax: "4K 60fps",
      batteryCapacity: "5800 mAh",
      charging: "80W SUPERVOOC wired, 30W AirVOOC wireless",
      weight: "195 g",
      dimensions: "162.8 x 76.4 x 7.3 mm",
      build: "Glass back, Aluminium frame",
      ipRating: "IP69",
      network: "5G, LTE-A",
      wifi: "Wi-Fi 6 (802.11ax)",
      bluetooth: "5.3",
      nfc: "Ya",
      usb: "USB 2.0, USB-C",
      fingerprint: "In-display optical",
      faceUnlock: "Ya",
      wirelessCharging: "Ya, 30W AirVOOC",
      reverseCharging: "Ya, 10W",
      simSlots: "Dual SIM (nano + nano)",
    },
  },

  // ── VIVO ──────────────────────────────────────────────
  {
    id: "vivo-x200-pro",
    brand: "Vivo",
    name: "X200 Pro",
    launchYear: 2025,
    priceRange: "Rp 15jt - 18jt",
    imageUrl: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400&q=80",
    specs: {
      screenSize: "6.78 inci",
      resolution: "2800 x 1260 px (FHD+, 452 ppi)",
      displayType: "LTPO AMOLED, Dolby Vision",
      refreshRate: "1-120Hz Adaptive",
      brightness: "Up to 4500 nits (peak)",
      processor: "MediaTek Dimensity 9400 (3nm)",
      gpu: "Immortalis-G925 MC12",
      ram: "16 GB",
      storage: "512 GB",
      mainCamera: "50 MP f/1.57, OIS, Zeiss optics",
      ultrawide: "50 MP f/2.0, 119° FoV",
      telephoto: "200 MP f/2.27 (3.7x periscope), OIS",
      frontCamera: "32 MP f/2.0",
      videoMax: "4K 120fps, 8K (Korea/China variant)",
      batteryCapacity: "6000 mAh",
      charging: "90W FlashCharge wired, 30W wireless",
      weight: "223 g",
      dimensions: "162.4 x 76.0 x 8.5 mm",
      build: "Glass back, Aluminium frame",
      ipRating: "IP69 + IP68",
      network: "5G (sub-6), LTE-A",
      wifi: "Wi-Fi 7 (802.11be)",
      bluetooth: "5.4",
      nfc: "Ya",
      usb: "USB 3.2 Gen 1 (10 Gbps), USB-C",
      fingerprint: "Ultrasonic in-display",
      faceUnlock: "Ya",
      wirelessCharging: "Ya, 30W",
      reverseCharging: "Ya, 5W",
      simSlots: "Dual SIM (nano + nano)",
    },
  },
  {
    id: "vivo-v40-pro",
    brand: "Vivo",
    name: "V40 Pro",
    launchYear: 2024,
    priceRange: "Rp 5jt - 7jt",
    imageUrl: "https://images.unsplash.com/photo-1563191911-e65f4c9e80b2?w=400&q=80",
    specs: {
      screenSize: "6.78 inci",
      resolution: "2800 x 1260 px (FHD+, 452 ppi)",
      displayType: "AMOLED 120Hz, Dolby Vision",
      refreshRate: "120Hz",
      brightness: "Up to 4500 nits (peak)",
      processor: "MediaTek Dimensity 9200+ (4nm)",
      gpu: "Immortalis-G715 MC11",
      ram: "12 GB",
      storage: "256 GB / 512 GB",
      mainCamera: "50 MP f/1.88, OIS, Zeiss optics",
      ultrawide: "50 MP f/2.0, 119° FoV",
      telephoto: "50 MP f/2.0 (2x), OIS",
      frontCamera: "50 MP f/2.0, autofocus",
      videoMax: "4K 60fps",
      batteryCapacity: "5500 mAh",
      charging: "80W FlashCharge wired",
      weight: "192 g",
      dimensions: "164.2 x 75.0 x 7.5 mm",
      build: "Glass back, Aluminium frame",
      ipRating: "IP68",
      network: "5G, LTE-A",
      wifi: "Wi-Fi 6 (802.11ax)",
      bluetooth: "5.3",
      nfc: "Ya",
      usb: "USB 2.0, USB-C",
      fingerprint: "In-display optical",
      faceUnlock: "Ya",
      wirelessCharging: "Tidak",
      reverseCharging: "Ya (wired 5W)",
      simSlots: "Dual SIM (nano + nano)",
    },
  },

  // ── REALME ─────────────────────────────────────────────
  {
    id: "realme-gt-6",
    brand: "Realme",
    name: "Realme GT 6",
    launchYear: 2024,
    priceRange: "Rp 4jt - 6jt",
    imageUrl: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400&q=80",
    specs: {
      screenSize: "6.78 inci",
      resolution: "2780 x 1264 px (FHD+, 450 ppi)",
      displayType: "LTPO AMOLED 120Hz, Dolby Vision",
      refreshRate: "1-120Hz Adaptive",
      brightness: "Up to 6000 nits (peak)",
      processor: "MediaTek Dimensity 9200+ (4nm)",
      gpu: "Immortalis-G715 MC11",
      ram: "12 GB / 16 GB",
      storage: "256 GB / 512 GB",
      mainCamera: "50 MP f/1.69, OIS",
      ultrawide: "8 MP f/2.2, 112° FoV",
      telephoto: "Tidak (digital zoom 10x)",
      frontCamera: "32 MP f/2.5",
      videoMax: "4K 60fps",
      batteryCapacity: "5500 mAh",
      charging: "120W UltraCharge (wired)",
      weight: "191 g",
      dimensions: "162.0 x 75.1 x 8.6 mm",
      build: "Glass back, Plastic frame",
      ipRating: "IP65",
      network: "5G, LTE-A",
      wifi: "Wi-Fi 7 (802.11be)",
      bluetooth: "5.3",
      nfc: "Ya",
      usb: "USB 2.0, USB-C",
      fingerprint: "In-display optical",
      faceUnlock: "Ya",
      wirelessCharging: "Tidak",
      reverseCharging: "Ya (wired 5W)",
      simSlots: "Dual SIM (nano + nano)",
    },
  },
  {
    id: "realme-13-plus",
    brand: "Realme",
    name: "Realme 13+",
    launchYear: 2024,
    priceRange: "Rp 3jt - 4jt",
    imageUrl: "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=400&q=80",
    specs: {
      screenSize: "6.67 inci",
      resolution: "2400 x 1080 px (FHD+, 395 ppi)",
      displayType: "AMOLED 120Hz",
      refreshRate: "120Hz",
      brightness: "Up to 2000 nits (HBM)",
      processor: "MediaTek Dimensity 7300 Energy (4nm)",
      gpu: "Mali-G615 MC4",
      ram: "8 GB / 12 GB",
      storage: "256 GB",
      mainCamera: "50 MP f/1.88, OIS, Sony LYT-600",
      ultrawide: "8 MP f/2.2, 112° FoV",
      telephoto: "Tidak (digital zoom 4x)",
      frontCamera: "16 MP f/2.4",
      videoMax: "4K 30fps",
      batteryCapacity: "5000 mAh",
      charging: "80W UltraCharge (wired)",
      weight: "180 g",
      dimensions: "160.6 x 73.9 x 7.6 mm",
      build: "Glass back, Plastic frame",
      ipRating: "IP65",
      network: "5G, LTE-A",
      wifi: "Wi-Fi 6 (802.11ax)",
      bluetooth: "5.3",
      nfc: "Ya",
      usb: "USB 2.0, USB-C",
      fingerprint: "In-display optical",
      faceUnlock: "Ya",
      wirelessCharging: "Tidak",
      reverseCharging: "Ya (wired 5W)",
      simSlots: "Hybrid: nano-SIM + microSD",
    },
  },
];

export const brands = ["Apple", "Samsung", "Xiaomi", "Oppo", "Vivo", "Realme"] as const;
export type Brand = typeof brands[number];

export const comparisonCategories = [
  {
    label: "Display",
    icon: "📱",
    specs: ["screenSize", "resolution", "displayType", "refreshRate", "brightness"] as const,
  },
  {
    label: "Performa",
    icon: "⚡",
    specs: ["processor", "gpu", "ram", "storage"] as const,
  },
  {
    label: "Kamera",
    icon: "📷",
    specs: ["mainCamera", "ultrawide", "telephoto", "frontCamera", "videoMax"] as const,
  },
  {
    label: "Baterai",
    icon: "🔋",
    specs: ["batteryCapacity", "charging"] as const,
  },
  {
    label: "Body",
    icon: "📐",
    specs: ["weight", "dimensions", "build", "ipRating"] as const,
  },
  {
    label: "Konektivitas",
    icon: "📡",
    specs: ["network", "wifi", "bluetooth", "nfc", "usb"] as const,
  },
  {
    label: "Fitur Tambahan",
    icon: "✨",
    specs: ["fingerprint", "faceUnlock", "wirelessCharging", "reverseCharging", "simSlots"] as const,
  },
] as const;

export const specLabels: Record<keyof PhoneSpec["specs"], string> = {
  screenSize: "Ukuran Layar",
  resolution: "Resolusi",
  displayType: "Tipe Display",
  refreshRate: "Refresh Rate",
  brightness: "Kecerahan",
  processor: "Prosesor",
  gpu: "GPU",
  ram: "RAM",
  storage: "Penyimpanan",
  mainCamera: "Kamera Utama",
  ultrawide: "Kamera Ultrawide",
  telephoto: "Kamera Telefoto",
  frontCamera: "Kamera Depan",
  videoMax: "Video Maks",
  batteryCapacity: "Kapasitas Baterai",
  charging: "Pengisian",
  weight: "Berat",
  dimensions: "Dimensi",
  build: "Material",
  ipRating: "Rating IP",
  network: "Jaringan",
  wifi: "Wi-Fi",
  bluetooth: "Bluetooth",
  nfc: "NFC",
  usb: "USB",
  fingerprint: "Fingerprint",
  faceUnlock: "Face Unlock",
  wirelessCharging: "Wireless Charging",
  reverseCharging: "Reverse Charging",
  simSlots: "Slot SIM",
};